package config

import "encoding/json"

// Status object as generated by the status scripts
type Status struct {
	Online  bool
	Players uint
	Uptime  uint
	Extra   struct {
		Name  string
		Value string
	} `json:"extra,omitempty"`
}

// StatusFromString will generate a status object from the string as returned by the api
func StatusFromString(statusString string) *Status {
	var status Status

	err := json.Unmarshal([]byte(statusString), &status)
	if err != nil {
		return nil
	}

	return &status
}
