title: "Minecraft server"
description: ""
icon: ".examples/minecraft/icon.jpg"
commands:
    status: ".examples/minecraft/status.sh"
    start: ".examples/minecraft/start.sh"
    stop: ".examples/minecraft/stop.sh"
files:
    something: some/config/file.cfg
